name: PyPi Publish
on: [ workflow_dispatch ]

jobs:
  macos_build:
    name: Mac OS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install TensorFlow
        run: |
          pip install tensorflow_macos
      - name: Build
        run: |
          make metal_lib
          make metal_kernel
      - name: Test
        run: make test
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build devcontainer
        run: |
          cd .devcontainer
          docker buildx build -t devcontainer --platform=linux/x86_64 .
      - name: Build
        run: |
          cd .devcontainer
          ./run_docker.sh make cpu_kernel
          ./run_docker.sh make cuda_lib
          ./run_docker.sh make cuda_kernel
      - name: Test
        run: |
          cd .devcontainer
          ./run_docker.sh "make test"
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true