name: PyPi Publish
on: [ workflow_dispatch ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          docker buildx build -t devcontainer --platform=linux/amd64 .
      - name: Build Kernel
        run: |
          docker run --platform=linux/amd64 \
            --mount type=bind,source="$(realpath "$(pwd)")",target="/tensorflow_nearest_neighbours" \
            --rm devcontainer tox run
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true