name: PyPi Publish
on: [ workflow_dispatch ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build devcontainer
        run: |
          cd .devcontainer
          docker buildx build -t devcontainer --platform=linux/x86_64 .
      - name: Build
        run: |
          cd .devcontainer
          ./run.sh make cuda_kernel
      - name: Test
        run: |
          cd .devcontainer
          ./run.sh make test
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true