name: PyPi Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos_build:
    name: PyPi Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: build
        run: make cpu_kernel
      - name: test
        run: make test
  linux_build:
    name: PyPi Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: build
        run: make cpu_kernel
      - name: test
        run: make test