name: Run Test
on: [ push ]

jobs:
  test_linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tensorflow==2.11.0
          apt-get install clang
      - name: Build Kernel
        run: |
          mkdir build
          make cpu_kernel
      - name: Test
        run: make test
  test_macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tensorflow==2.11.0
      - name: Build Kernel
        run: |
          mkdir build
          make cpu_kernel
      - name: Test
        run: make test