name: Run Test
on: [ push ]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Install dependencies
        shell: bash
        run: |
          pip install tensorflow==2.11.0