name: Test
on: [ pull_request ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          docker buildx build -t devcontainer --platform=linux/amd64 --file Dockerfile.build .
      - name: Build Kernel
        run: |
          docker run --platform=linux/amd64 \
            --mount type=bind,source="$(realpath "$(pwd)")",target="/tensorflow_nearest_neighbours" \
            --rm devcontainer tox run