name: Test
on: [ pull_request ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: |
          docker buildx build -t container --platform=linux/x86_64 .
      - name: Test Build kernel
        run: |
          docker run container