name: Test
on: [ pull_request ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          docker buildx build -t devcontainer --platform=linux/x86_64 .
      - name: Build Kernel
        run: |
          ./run.sh tox run