name: Test
on: [ pull_request ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          docker buildx build -t container --platform=linux/x86_64 .
      - name: Build Kernel
        run: |
          ./run.sh make cuda_kernel
      - name: Test
        run: |
          ./run.sh python << EOF
            setup.py bdbist_wheel
            python -m pip install dist/*.whl
            python -m unittest test/nearest_neighbours_test.py
          EOF