name: Test
on: [ pull_request ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: devcontainer
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build Kernel
        run: |
          docker run \
            --mount type=bind,source="$(realpath "$(pwd)")",target="/tensorflow_nearest_neighbours" \
            --rm devcontainer tox run